---

- hosts: all
  become: yes
  vars:
    zabbix_server: "51.250.106.163"
    zabbix_hostname: "{{ ansible_hostname }}"      
  tasks:

  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest

  -  name: Configure Zabbix agent
     lineinfile:
       state: present
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '^(\s*)[#]?{{ item.search }}(: )*'
       line: '{{ item.replace }}'
     with_items:
      - { search: '^Hostname=', replace: 'Hostname={{ zabbix_hostname }}' } 
      - { search: '^Server=', replace: 'Server={{ zabbix_server }}' }
    
  - name: Start and enable Zabbix agent service
    service:
     name: zabbix-agent
     enabled: yes
     state: started
